#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "Inchi" for configuration "Release"
SET_PROPERTY(TARGET Inchi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Inchi PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Inchi.lib"
  )

# Import target "RDInchiLib" for configuration "Release"
SET_PROPERTY(TARGET RDInchiLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(RDInchiLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/RDInchiLib.lib"
  )

# Import target "avalon_clib" for configuration "Release"
SET_PROPERTY(TARGET avalon_clib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(avalon_clib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/avalon_clib.lib"
  )

# Import target "AvalonLib" for configuration "Release"
SET_PROPERTY(TARGET AvalonLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(AvalonLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/AvalonLib.lib"
  )

# Import target "RDGeneral" for configuration "Release"
SET_PROPERTY(TARGET RDGeneral APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(RDGeneral PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/RDGeneral.lib"
  )

# Import target "RDBoost" for configuration "Release"
SET_PROPERTY(TARGET RDBoost APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(RDBoost PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/RDBoost.lib"
  )

# Import target "DataStructs" for configuration "Release"
SET_PROPERTY(TARGET DataStructs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(DataStructs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/DataStructs.lib"
  )

# Import target "RDGeometryLib" for configuration "Release"
SET_PROPERTY(TARGET RDGeometryLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(RDGeometryLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/RDGeometryLib.lib"
  )

# Import target "Alignment" for configuration "Release"
SET_PROPERTY(TARGET Alignment APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Alignment PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Alignment.lib"
  )

# Import target "EigenSolvers" for configuration "Release"
SET_PROPERTY(TARGET EigenSolvers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(EigenSolvers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/EigenSolvers.lib"
  )

# Import target "Optimizer" for configuration "Release"
SET_PROPERTY(TARGET Optimizer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Optimizer PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Optimizer.lib"
  )

# Import target "ForceField" for configuration "Release"
SET_PROPERTY(TARGET ForceField APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ForceField PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/ForceField.lib"
  )

# Import target "DistGeometry" for configuration "Release"
SET_PROPERTY(TARGET DistGeometry APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(DistGeometry PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/DistGeometry.lib"
  )

# Import target "Catalogs" for configuration "Release"
SET_PROPERTY(TARGET Catalogs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Catalogs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Catalogs.lib"
  )

# Import target "GraphMol" for configuration "Release"
SET_PROPERTY(TARGET GraphMol APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(GraphMol PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/GraphMol.lib"
  )

# Import target "Depictor" for configuration "Release"
SET_PROPERTY(TARGET Depictor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Depictor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Depictor.lib"
  )

# Import target "SmilesParse" for configuration "Release"
SET_PROPERTY(TARGET SmilesParse APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(SmilesParse PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/SmilesParse.lib"
  )

# Import target "FileParsers" for configuration "Release"
SET_PROPERTY(TARGET FileParsers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(FileParsers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/FileParsers.lib"
  )

# Import target "SubstructMatch" for configuration "Release"
SET_PROPERTY(TARGET SubstructMatch APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(SubstructMatch PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/SubstructMatch.lib"
  )

# Import target "ChemReactions" for configuration "Release"
SET_PROPERTY(TARGET ChemReactions APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ChemReactions PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/ChemReactions.lib"
  )

# Import target "ChemTransforms" for configuration "Release"
SET_PROPERTY(TARGET ChemTransforms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ChemTransforms PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/ChemTransforms.lib"
  )

# Import target "Subgraphs" for configuration "Release"
SET_PROPERTY(TARGET Subgraphs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Subgraphs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Subgraphs.lib"
  )

# Import target "FragCatalog" for configuration "Release"
SET_PROPERTY(TARGET FragCatalog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(FragCatalog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/FragCatalog.lib"
  )

# Import target "Descriptors" for configuration "Release"
SET_PROPERTY(TARGET Descriptors APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Descriptors PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Descriptors.lib"
  )

# Import target "Fingerprints" for configuration "Release"
SET_PROPERTY(TARGET Fingerprints APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(Fingerprints PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/Fingerprints.lib"
  )

# Import target "PartialCharges" for configuration "Release"
SET_PROPERTY(TARGET PartialCharges APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(PartialCharges PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/PartialCharges.lib"
  )

# Import target "MolTransforms" for configuration "Release"
SET_PROPERTY(TARGET MolTransforms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MolTransforms PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/MolTransforms.lib"
  )

# Import target "ForceFieldHelpers" for configuration "Release"
SET_PROPERTY(TARGET ForceFieldHelpers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ForceFieldHelpers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/ForceFieldHelpers.lib"
  )

# Import target "DistGeomHelpers" for configuration "Release"
SET_PROPERTY(TARGET DistGeomHelpers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(DistGeomHelpers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/DistGeomHelpers.lib"
  )

# Import target "MolAlign" for configuration "Release"
SET_PROPERTY(TARGET MolAlign APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MolAlign PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/MolAlign.lib"
  )

# Import target "MolChemicalFeatures" for configuration "Release"
SET_PROPERTY(TARGET MolChemicalFeatures APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MolChemicalFeatures PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/MolChemicalFeatures.lib"
  )

# Import target "ShapeHelpers" for configuration "Release"
SET_PROPERTY(TARGET ShapeHelpers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ShapeHelpers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/ShapeHelpers.lib"
  )

# Import target "MolCatalog" for configuration "Release"
SET_PROPERTY(TARGET MolCatalog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MolCatalog PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/MolCatalog.lib"
  )

# Import target "MolDraw2D" for configuration "Release"
SET_PROPERTY(TARGET MolDraw2D APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MolDraw2D PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/MolDraw2D.lib"
  )

# Import target "FMCS" for configuration "Release"
SET_PROPERTY(TARGET FMCS APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(FMCS PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/FMCS.lib"
  )

# Import target "MolHash" for configuration "Release"
SET_PROPERTY(TARGET MolHash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MolHash PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/MolHash.lib"
  )

# Import target "SLNParse" for configuration "Release"
SET_PROPERTY(TARGET SLNParse APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(SLNParse PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/SLNParse.lib"
  )

# Import target "SimDivPickers" for configuration "Release"
SET_PROPERTY(TARGET SimDivPickers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(SimDivPickers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/SimDivPickers.lib"
  )

# Import target "hc" for configuration "Release"
SET_PROPERTY(TARGET hc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/hc.lib"
  )

# Import target "InfoTheory" for configuration "Release"
SET_PROPERTY(TARGET InfoTheory APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(InfoTheory PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/InfoTheory.lib"
  )

# Import target "ChemicalFeatures" for configuration "Release"
SET_PROPERTY(TARGET ChemicalFeatures APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ChemicalFeatures PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "c:/Boost/boost32_156/lib32-msvc-10.0/boost_system-vc100-mt-1_56.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/glandrum/RDKit_2015_03_1/lib/ChemicalFeatures.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
